# Generated by Django 3.1.6 on 2021-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-date']},
        ),
        migrations.AddConstraint(
            model_name='utilitymeter',
            constraint=models.UniqueConstraint(fields=('customer', 'type'), name='customer_type'),
        ),
    ]
